#!/bin/sh
# Quickly add a existing repo as a submodule

# usage: git-add-submodule <path-to-repo>

# Utils
# text formatting 
_reset="\e[0;0m"
_red="\e[1;31m"
_green="\e[1;32m"
_yellow="\e[1;33m"
_blue="\e[1;34m"
_strong="\e[1;39m"

# Main

# TODO: Support glob as input

if ! [ $# -eq 1 ]; then
  printf "ERROR: Wrong number of arguments.\n"
  exit 1
else
  _path="$1"
fi

if ! [ -d "$_path" ]; then
  printf "ERROR: Path isn't a valid directory.\n"
  exit 1
fi

# make path absolute
_abs_path="$(readlink -f "$_path")"
_project_root=$(git -C "$_path" rev-parse --show-toplevel)

if [ "$_abs_path" != "$_project_root" ]; then
  printf "ERROR: Path isn't the root of a Git repository.\n"
  exit 1
fi

_repo_url="$(git -C "$_path" remote get-url origin)"

git submodule add "$_repo_url" "$_path"
